### ISSUE TITLE
Action Group Action Names Unclear When Using AGExt

### ISSUE THREAD

**Issue by JustaSimpleUser** [JPLRepo/TarsierSpaceTechnology#60]
With the Action Group Extended (AGExt) mod installed, the text displayed for the Science Storage devices' actions don't clearly describe the function they perform ("fillDrive" and "expfileDrive").  Although there are only two actions and their functions can be deduced, unambiguous action text would make their functions clear.

**Comment by JPLRepo** [comment]
Something perhaps to discuss with the mod author of that mod?
This mod does not support that mod...
and I have no idea what that mod is doing. But seems it is referring to internal code method names instead of the attributes on the methods which is what all of KSP uses....
So nope. Not going to change it.

**Comment by JustaSimpleUser** [comment]
Understood. I'll raise it with LinuxGuruGamer.  Thanks.
